# Generated by Django 6.0.4 on 2026-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('poste', models.CharField(max_length=20)),
            ],
        ),
    ]
